import { createAdapterBindings } from '../adapterBindings.js';
import { buildLineageOptions } from './lineageOptions.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSpeciesAdapter("Tiefling_XPHB", function (s) {
  let specs = getGenericSpeciesChoiceSpecs(s);
  specs = specs.filter(function (x) { return !String(x.key || '').startsWith('species_resist'); });

  const legacyOptions = buildLineageOptions(s._versions, { parentName: 'Tiefling', suffixes: ['Legacy'] });

  specs.push({ key: 'species_version', label: 'Fiendish Legacy', type: 'option', options: legacyOptions, count: 1, level: 1 });
  specs.push({ key: 'species_spell_ability', label: 'Spellcasting Ability (Tiefling)', type: 'ability_choice', from: ['int', 'wis', 'cha'], count: 1, level: 1 });
  return specs;
});

registerSpeciesSheetCommonChoiceMeta("Tiefling_XPHB", {
  labels: {
    species_version: 'Fiendish Legacy',
    species_spell_ability: 'Spellcasting Ability (Tiefling)',
  },
});
registerSpeciesSheetEffects("Tiefling_XPHB", [
  {
    type: 'resistance-choice',
    key: 'species_version',
    map: {
      abyssal: 'Poison',
      chthonic: 'Necrotic',
      infernal: 'Fire',
    },
    minLevel: 1,
    note: 'Fiendish Legacy',
  },
  {
    type: 'sense',
    senseType: 'darkvision',
    value: 120,
    minLevel: 1,
    note: 'Abyssal Legacy',
    requiredChoice: { key: 'species_version', value: 'Abyssal' },
  },
]);

registerSpeciesRuntimeConfig("Tiefling_XPHB", {
  spellcasting: {
    alwaysKnownSpells: [
      // Abyssal Legacy
      { name: 'Thaumaturgy',       level: 0, minLevel: 1, source: 'Abyssal Legacy',  sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Abyssal' } },
      { name: 'Poison Spray',      level: 0, minLevel: 1, source: 'Abyssal Legacy',  sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Abyssal' } },
      { name: 'Ray of Sickness',   level: 1, minLevel: 3, source: 'Abyssal Legacy',  sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Abyssal' }, freeCast: { maxUses: 1, recharge: 'longRest', canAlsoUseSlots: true } },
      { name: 'Hold Person',       level: 2, minLevel: 5, source: 'Abyssal Legacy',  sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Abyssal' }, freeCast: { maxUses: 1, recharge: 'longRest', canAlsoUseSlots: true } },
      // Chthonic Legacy
      { name: 'Thaumaturgy',       level: 0, minLevel: 1, source: 'Chthonic Legacy', sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Chthonic' } },
      { name: 'Chill Touch',       level: 0, minLevel: 1, source: 'Chthonic Legacy', sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Chthonic' } },
      { name: 'False Life',        level: 1, minLevel: 3, source: 'Chthonic Legacy', sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Chthonic' }, freeCast: { maxUses: 1, recharge: 'longRest', canAlsoUseSlots: true } },
      { name: 'Ray of Enfeeblement', level: 2, minLevel: 5, source: 'Chthonic Legacy', sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Chthonic' }, freeCast: { maxUses: 1, recharge: 'longRest', canAlsoUseSlots: true } },
      // Infernal Legacy
      { name: 'Thaumaturgy',       level: 0, minLevel: 1, source: 'Infernal Legacy', sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Infernal' } },
      { name: 'Fire Bolt',         level: 0, minLevel: 1, source: 'Infernal Legacy', sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Infernal' } },
      { name: 'Hellish Rebuke',    level: 1, minLevel: 3, source: 'Infernal Legacy', sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Infernal' }, freeCast: { maxUses: 1, recharge: 'longRest', canAlsoUseSlots: true } },
      { name: 'Darkness',          level: 2, minLevel: 5, source: 'Infernal Legacy', sourceType: 'species', requiredChoice: { key: 'species_version', value: 'Infernal' }, freeCast: { maxUses: 1, recharge: 'longRest', canAlsoUseSlots: true } },
    ],
  },
});

}
