import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Barbarian_Zealot", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Barbarian_Zealot", [
  { name: "Divine Fury", icon: "", cat: "attack", uses: "Passive", minLevel: 3,
  passive: true,
    rollers: [{ kind: 'damage', formula: ({ ownerLevel }) => `1d6+${Math.floor(Number(ownerLevel||1)/2)}`, label: ({ formula }) => `+${formula} necrotic/radiant` }],
    desc: "While Raging, the first creature you hit each turn with a weapon or Unarmed Strike takes extra damage equal to 1d6 + half your Barbarian level. You choose the damage type (Necrotic or Radiant) each time you deal this damage." },
  { name: "Warrior of the Gods", icon: "", cat: "bonus", uses: "Pool / LR", resKey: "zealot_warrior_pool", minLevel: 3,
    desc: "A divine pool of healing dice sustains you. Bonus Action: expend any number of d12s from your pool, roll them, and regain that many HP. Pool starts at 4d12 (grows to 5d12 at lv.6, 6d12 at lv.12, 7d12 at lv.17). Recharge: Long Rest." },
  { name: "Fanatical Focus", icon: "", cat: "reaction", uses: "1 / Rage", minLevel: 6,
    desc: "Once per active Rage, when you fail a saving throw, reroll it with a bonus equal to your Rage Damage bonus. You must use the new roll." },
  { name: "Zealous Presence", icon: "", cat: "bonus", uses: "1 / LR or Rage use", resKey: "zealous_presence", minLevel: 10,
    desc: "Bonus Action: unleash a battle cry infused with divine energy. Up to 10 other creatures of your choice within 60 ft gain Advantage on attack rolls and saving throws until the start of your next turn. 1/LR, or expend a use of your Rage (no action) to restore." },
  { name: "Rage of the Gods", icon: "", cat: "action", uses: "1 / LR", resKey: "zealot_rage_gods", minLevel: 14,
    desc: "When you activate your Rage, assume a divine warrior form for 1 minute or until you drop to 0 HP (1/LR). Three benefits while in this form — Flight: Fly Speed equal to your Speed, can hover; Resistance: Resistance to Necrotic, Psychic, and Radiant damage; Revivification: Reaction when a creature within 30 ft would drop to 0 HP, expend a use of your Rage to change its HP to a number equal to your Barbarian level instead." },
]);
registerSubclassSheetResources("Barbarian_Zealot", [
  { key: "zealot_warrior_pool", name: "Warrior of the Gods", icon: "heart", recharge: "LR",
    max: (lv) => lv >= 17 ? 7 : lv >= 12 ? 6 : lv >= 6 ? 5 : 4,
    pool: true, track: "used" },
  { key: "zealous_presence",    name: "Zealous Presence",   icon: "megaphone", recharge: "LR", max: () => 1 },
  { key: "zealot_rage_gods",    name: "Rage of the Gods",   icon: "flame",     recharge: "LR", max: () => 1 },
]);

registerSubclassSheetEffects("Barbarian_Zealot", [

  { type: "radiantOrNecroticDamage", minLevel: 3, note: "Divine Fury: extra damage once each turn while raging." },
  { type: "reroll", minLevel: 6, note: "Fanatical Focus: reroll a failed save while raging." },
  { type: "flySpeed", minLevel: 14, note: "Rage of the Gods: fly speed and resistance-related benefits while raging." },
]);
// [SheetRuntime] END

}

