import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Ranger_Winter Walker", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Ranger_Winter Walker", [
  {
    "name": "Frigid Explorer",
    "icon": "",
    "cat": "action",
    "uses": "Passive",
    "passive": true,
    "minLevel": 3,
    "desc": "Passive: Biting Cold — your weapon attacks and ranger spell attacks ignore Resistance to Cold damage. Frost Resistance — you have Resistance to Cold damage. Polar Strikes — once per turn when you hit with a weapon attack or ranger spell attack, deal an extra 1d4 Cold damage (1d6 at lv.11)."
  },
  {
    "name": "Hunter's Rime",
    "icon": "",
    "cat": "action",
    "uses": "On Hunter's Mark",
    "passive": true,
    "minLevel": 3,
    "desc": "When you cast Hunter's Mark: you gain Temporary HP equal to 1d10 + your Ranger level. While Hunter's Mark is active, the marked creature can't take the Disengage action."
  },
  {
    "name": "Fortifying Soul",
    "icon": "",
    "cat": "action",
    "uses": "1 / LR",
    "resKey": "winter_walker_fortify",
    "minLevel": 7,
    "desc": "Magic action: choose a number of creatures you can see within 30 ft up to your WIS modifier (min 1, can include yourself). Each chosen creature regains 1d10 + your Ranger level Hit Points and has Advantage on saving throws against the Frightened condition for 1 hour. Recharge: Long Rest."
  },
  {
    "name": "Chilling Retribution",
    "icon": "",
    "cat": "reaction",
    "uses": "WIS mod / LR",
    "resKey": "winter_walker_retribution",
    "minLevel": 11,
    "desc": "Reaction — when you take damage from an attack: the attacker must succeed on a WIS saving throw (DC = 8 + PB + WIS modifier) or be Stunned until the end of its next turn, and its Speed becomes 0 until the end of its next turn. Uses: WIS modifier (min 1) per Long Rest."
  },
  {
    "name": "Frozen Haunt",
    "icon": "",
    "cat": "action",
    "uses": "1 / LR",
    "resKey": "winter_walker_haunt",
    "minLevel": 15,
    "desc": "When you cast Hunter's Mark, you can enter a ghostly form for the duration of that spell (1/LR, or expend a level 4+ spell slot). While in ghostly form: Frozen Soul — Immunity to Cold damage; at the start of each of your turns, each creature within a 15-ft Emanation takes 2d4 Cold damage. Partially Incorporeal — immune to Grappled, Prone, and Restrained; you can move through creatures and objects as Difficult Terrain (take 1d10 Force damage if you end your turn inside an object)."
  }
]);
registerSubclassSheetResources("Ranger_Winter Walker", [
  {
    "key": "winter_walker_fortify",
    "name": "Fortifying Soul",
    "icon": "heart",
    "recharge": "LR",
    "max": () => 1
  },
  {
    "key": "winter_walker_retribution",
    "name": "Chilling Retribution",
    "icon": "zap",
    "recharge": "LR",
    "max": (lv, { wis } = {}) => Math.max(1, wis ?? 0)
  },
  {
    "key": "winter_walker_haunt",
    "name": "Frozen Haunt",
    "icon": "eye-off",
    "recharge": "LR",
    "max": () => 1
  }
]);
// [SheetRuntime] END

}

