import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Paladin_Ancients", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Paladin_Ancients", [
  { name: "Nature's Wrath", icon: "", cat: "action", uses: "1 Channel", resKey: "paladin_channel_div",
    desc: "Magic action: expend one use of Channel Divinity to conjure spectral vines. Each creature of your choice you can see within 15 ft must succeed on a STR saving throw (spell save DC) or have the Restrained condition for 1 minute. A Restrained creature repeats the save at the end of each of its turns, ending the effect on a success." },
  { name: "Aura of Warding", icon: "", cat: "action", uses: "Passive", minLevel: 7,
  passive: true,
    desc: "While conscious, you and friendly creatures within your Aura of Protection have Resistance to Necrotic, Psychic, and Radiant damage. Range: 10 ft (30 ft at lv.18)." },
  { name: "Undying Sentinel", icon: "", cat: "action", uses: "1 / LR", resKey: "ancients_undying_sentinel", minLevel: 15,
    desc: "When you are reduced to 0 HP and not killed outright, you can drop to 1 HP instead and regain HP equal to 3 times your Paladin level. You also can't be aged magically and cease visibly aging. Recharge: Long Rest." },
  { name: "Elder Champion", icon: "", cat: "bonus", uses: "1 / LR or lv5 slot", resKey: "ancients_elder_champion", minLevel: 20,
    desc: "Bonus Action: imbue your Aura of Protection with primal power for 1 minute (no action to end). Three benefits — Diminish Defiance: enemies in the aura have Disadvantage on saving throws against your spells and Channel Divinity; Regeneration: regain 10 HP at the start of each of your turns; Swift Spells: whenever you cast a spell with a casting time of an action, you can cast it using a Bonus Action instead. Recharge: LR, or expend a level 5 spell slot." },
]);
registerSubclassSheetResources("Paladin_Ancients", [
  { key: "ancients_undying_sentinel", name: "Undying Sentinel", icon: "shield", recharge: "LR", max: () => 1 },
  { key: "ancients_elder_champion",   name: "Elder Champion",   icon: "leaf",   recharge: "LR", max: () => 1 },
]);

if (typeof registerSubclassRuntimeConfig === "function") {
  registerSubclassRuntimeConfig("Paladin_Ancients", {
    spellcasting: {
      alwaysPreparedSpells: [
        { name: "Ensnaring Strike", minLevel: 3, level: 1 },
        { name: "Speak with Animals", minLevel: 3, level: 1 },
        { name: "Misty Step", minLevel: 5, level: 2 },
        { name: "Moonbeam", minLevel: 5, level: 2 },
        { name: "Plant Growth", minLevel: 9, level: 3 },
        { name: "Protection from Energy", minLevel: 9, level: 3 },
        { name: "Ice Storm", minLevel: 13, level: 4 },
        { name: "Stoneskin", minLevel: 13, level: 4 },
        { name: "Commune with Nature", minLevel: 17, level: 5 },
        { name: "Tree Stride", minLevel: 17, level: 5 }
      ],
    },
  });
}

registerSubclassSheetEffects("Paladin_Ancients", [

  { type: "resistance", damageTypes: ["Necrotic", "Psychic", "Radiant"], minLevel: 7, note: "Aura of Warding: applies while in Aura of Protection." },

]);
// [SheetRuntime] END

}

