import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Fighter_Psi Warrior", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Fighter_Psi Warrior", [
  { name: "Protective Field", icon: "", cat: "reaction", uses: "1 Psi Die", resKey: "psi_dice", minLevel: 3,
    desc: "Reaction when you or another creature you can see within 30 ft takes damage: expend one Psionic Energy Die, roll it, and reduce the damage taken by the number rolled plus your INT modifier (minimum reduction of 1)." },
  { name: "Psionic Strike", icon: "", cat: "attack", uses: "1 Psi Die / turn", resKey: "psi_dice", minLevel: 3,
    rollFormula: ({ ownerLevel }) => {
      const lv = Number(ownerLevel || 1);
      const die = lv >= 17 ? 'd12' : lv >= 11 ? 'd10' : lv >= 5 ? 'd8' : 'd6';
      return `1${die}+INT`;
    },
    rollButtonLabel: ({ formula }) => `+${formula} force`,
    rollKind: "damage",
    desc: "Once per turn, immediately after hitting a target within 30 ft with a weapon and dealing damage, expend one Psionic Energy Die: deal extra Force damage equal to the roll + your INT modifier." },
  { name: "Telekinetic Movement", icon: "", cat: "action", uses: "1 / SR+LR or Psi Die", resKey: "telekinetic_movement", minLevel: 3,
    desc: "Magic action: choose one target within 30 ft — a loose Large or smaller object, or a willing creature other than you. Transport it up to 30 ft to an unoccupied space you can see. If target is a Tiny object, can move it to or from your hand instead. 1/SR or LR, or expend a Psionic Energy Die (no action) to restore." },
  { name: "Psi-Powered Leap", icon: "", cat: "bonus", uses: "1 / SR+LR or Psi Die", resKey: "psi_leap", minLevel: 7,
    desc: "Bonus Action: gain a Fly Speed equal to twice your Speed until end of the current turn. 1/SR or LR, or expend a Psionic Energy Die (no action) to restore." },
  { name: "Telekinetic Thrust", icon: "", cat: "attack", uses: "On Psionic Strike", minLevel: 7,
  passive: true,
    desc: "When you deal damage with Psionic Strike, force the target to make a STR save (DC = 8 + INT mod + PB). On a failed save, choose one: give the target the Prone condition, or transport it up to 10 ft horizontally." },
  { name: "Guarded Mind", icon: "", cat: "action", uses: "Passive + Psi Die", resKey: "psi_dice", minLevel: 10,
  passive: true,
    desc: "Resistance to Psychic damage. If you start your turn with the Charmed or Frightened condition, you can expend a Psionic Energy Die (no action required) to end every effect on you causing those conditions." },
  { name: "Bulwark of Force", icon: "", cat: "bonus", uses: "1 / LR or Psi Die", resKey: "bulwark_force", minLevel: 15,
    desc: "Bonus Action: choose creatures within 30 ft (can include yourself) up to your INT modifier (min 1). Each gains Half Cover for 1 minute or until you have the Incapacitated condition. 1/LR, or expend a Psionic Energy Die (no action) to restore." },
  { name: "Telekinetic Master", icon: "", cat: "action", uses: "1 / LR or Psi Die", resKey: "telekinetic_master", minLevel: 18,
    desc: "Telekinesis is always prepared for you. Cast it without a spell slot or components (INT spellcasting ability). While concentrating on it (including the turn you cast it), you can make one attack with a weapon as a Bonus Action on each of your turns. 1/LR, or expend a Psionic Energy Die (no action) to restore." },
]);
registerSubclassSheetResources("Fighter_Psi Warrior", [
  { key: "psi_dice", name: "Psionic Energy Dice", icon: "orbit", recharge: "LR",
    max: (lv) => lv >= 17 ? 12 : lv >= 13 ? 10 : lv >= 9 ? 8 : lv >= 5 ? 6 : 4,
    die: (lv) => lv >= 17 ? "d12" : lv >= 11 ? "d10" : lv >= 5 ? "d8" : "d6",
    pool: true, track: "used" },
  { key: "telekinetic_movement", name: "Telekinetic Movement", icon: "wind",   recharge: "SR", max: () => 1 },
  { key: "psi_leap",             name: "Psi-Powered Leap",     icon: "arrow-up", recharge: "SR", max: () => 1 },
  { key: "bulwark_force",        name: "Bulwark of Force",     icon: "shield", recharge: "LR", max: () => 1 },
  { key: "telekinetic_master",   name: "Telekinetic Master",   icon: "zap",    recharge: "LR", max: () => 1 },
]);
if (typeof registerSubclassRuntimeConfig === "function") {
  registerSubclassRuntimeConfig("Fighter_Psi Warrior", {
    spellcasting: {
      ability: "int",
      alwaysPreparedSpells: [
        { name: "Telekinesis", minLevel: 18, level: 5 },
      ],
    },
  });
}

registerSubclassSheetEffects("Fighter_Psi Warrior", [

  { type: "damageReduction", minLevel: 3, note: "Protective Field: reduce damage to a creature within 30 ft by Psionic Energy Die + INT mod." },
  { type: "forceDamage", minLevel: 3, note: "Psionic Strike: extra Force damage using Psionic Energy Die + INT mod." },
  { type: "conditionRemoval", conditions: ["Charmed", "Frightened"], minLevel: 10, note: "Guarded Mind." },
  { type: "resistance", damageTypes: ["Psychic"], minLevel: 10, note: "Guarded Mind." },
]);
// [SheetRuntime] END

}

