import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Sorcerer_Clockwork Soul", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Sorcerer_Clockwork Soul", [
  {
    "name": "Restore Balance",
    "icon": "",
    "cat": "reaction",
    "uses": "CHA mod / LR",
    "resKey": "clockwork_restore",
    "minLevel": 3,
    "desc": "Reaction when a creature you can see within 60 ft is about to roll a d20 with Advantage or Disadvantage: prevent the roll from being affected by Advantage or Disadvantage. Uses: CHA modifier (min 1) per Long Rest."
  },
  {
    "name": "Bastion of Law",
    "icon": "",
    "cat": "action",
    "uses": "1–5 Sorcery Points",
    "resKey": "sorc_pts",
    "minLevel": 6,
    "desc": "Magic action: expend 1–5 Sorcery Points to create a ward around yourself or another creature you can see within 30 ft. The ward has a number of d8s equal to the points spent. When the warded creature takes damage, it can expend any number of those dice (no action), roll them, and reduce the damage by the total. The ward lasts until you finish a Long Rest or use this feature again."
  },
  {
    "name": "Trance of Order",
    "icon": "",
    "cat": "bonus",
    "uses": "1 / LR",
    "resKey": "clockwork_trance",
    "minLevel": 14,
    "desc": "Bonus Action: enter this state for 1 minute. Attack rolls against you can't benefit from Advantage, and whenever you make a D20 Test (attack roll, ability check, or saving throw), you can treat a d20 roll of 9 or lower as a 10. 1/LR, or spend 5 Sorcery Points (no action) to restore this use."
  },
  {
    "name": "Clockwork Cavalcade",
    "icon": "",
    "cat": "action",
    "uses": "1 / LR",
    "resKey": "clockwork_cavalcade",
    "minLevel": 18,
    "desc": "Magic action: summon spirits of order in a 30-ft Cube originating from you. The spirits create these effects before vanishing: restore up to 100 Hit Points, divided as you choose among any number of creatures of your choice in the Cube; damaged objects entirely in the Cube are repaired instantly; every spell of level 6 and lower ends on creatures and objects of your choice in the Cube. 1/LR, or spend 7 Sorcery Points (no action) to restore this use."
  }
]);
registerSubclassSheetResources("Sorcerer_Clockwork Soul", [
  {
    "key": "clockwork_restore",
    "name": "Restore Balance",
    "icon": "settings",
    "recharge": "LR",
    "max": (lv, { cha } = {}) => Math.max(1, cha ?? 0)
  },
  {
    "key": "clockwork_trance",
    "name": "Trance of Order",
    "icon": "clock",
    "recharge": "LR",
    "max": () => 1
  },
  {
    "key": "clockwork_cavalcade",
    "name": "Clockwork Cavalcade",
    "icon": "cog",
    "recharge": "LR",
    "max": () => 1
  }
]);

registerSubclassSheetEffects("Sorcerer_Clockwork Soul", [

  { type: "d20-floor", minRoll: 10, minLevel: 14, note: "Trance of Order: treat d20 rolls of 9 or lower as 10 while active." },

]);
// [SheetRuntime] END

}

