import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Sorcerer_Spellfire", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Sorcerer_Spellfire", [
  {
    "name": "Spellfire Burst",
    "icon": "",
    "cat": "action",
    "uses": "Once / turn (on SP spend)",
    "minLevel": 3,
    "desc": "Once per turn, when you spend 1 or more Sorcery Points as a Magic action or Bonus action on your turn, choose one: Bolstering Flames — you or a creature within 30 ft you can see gains 1d4 + CHA modifier Temporary HP (increases to 1d4 + CHA modifier + Sorcerer level at lv.14). Radiant Fire — a creature within 30 ft you can see takes 1d4 Fire or Radiant damage (your choice when you use the option; increases to 1d8 at lv.14). No saving throw."
  },
  {
    "name": "Absorb Spells",
    "icon": "",
    "cat": "reaction",
    "uses": "On Counterspell",
    "passive": true,
    "minLevel": 6,
    "desc": "Counterspell is always prepared for you. When you cast Counterspell and the target fails its CON saving throw (its spell is countered), you regain 1d4 Sorcery Points."
  },
  {
    "name": "Crown of Spellfire",
    "icon": "",
    "cat": "action",
    "uses": "1 / LR",
    "resKey": "crown_of_spellfire",
    "minLevel": 18,
    "desc": "When you activate Innate Sorcery, you can also activate Crown of Spellfire (1/LR, or expend 5 Sorcery Points) for the same duration. While active: Burning Life Force — once per turn when you take damage, expend up to your CHA modifier (min 1) Hit Dice, roll them, and reduce the damage by the total rolled. Flight — gain Fly Speed 60 ft with the Hover property. Spell Avoidance — when a spell or magical effect forces you to make a saving throw, a success means you take no damage; a failure (while not Incapacitated) means you take half damage instead."
  }
]);
registerSubclassSheetResources("Sorcerer_Spellfire", [
  {
    "key": "crown_of_spellfire",
    "name": "Crown of Spellfire",
    "icon": "flame",
    "recharge": "LR",
    "max": () => 1
  }
]);
if (typeof registerSubclassRuntimeConfig === "function") {
  registerSubclassRuntimeConfig("Sorcerer_Spellfire", {
    spellcasting: {
      alwaysPreparedSpells: [
        { name: "Counterspell", minLevel: 6, level: 3 },
      ],
    },
  });
}
// [SheetRuntime] END

}

