import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Warlock_Archfey", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Warlock_Archfey", [
  { name: "Steps of the Fey", icon: "sparkles", cat: "bonus", uses: "CHA mod / LR", resKey: "archfey_steps", minLevel: 3,
    rollers: [{ kind: 'tempHp', formula: "1d10" }],
    desc: "Bonus Action: cast Misty Step without expending a spell slot. When you teleport, choose one effect: Refreshing Step gives you 1d10 Temporary HP; Taunting Step forces creatures of your choice within 5 ft of your destination to make a WIS save or have Disadvantage on attacks against creatures other than you until the start of your next turn." },
  { name: "Misty Escape", icon: "sparkles", cat: "reaction", uses: "Pact Magic slot", minLevel: 6,
    rollers: [{ kind: 'damage', formula: "2d10", label: "Fey Curse 2d10 Psychic" }],
    desc: "Reaction when you take damage: expend one Pact Magic slot to cast Misty Step. After teleporting, choose Fey Refuge to become Invisible until the start of your next turn, or Fey Curse to force creatures within 5 ft of your origin or destination to make a WIS save or take 2d10 Psychic damage." },
  { name: "Beguiling Defenses", icon: "shield", cat: "reaction", uses: "1 / LR or Pact Magic slot", resKey: "archfey_beguiling", minLevel: 10,
    desc: "You are immune to Charmed. Reaction when hit by an attack: halve the damage, and the attacker must make a WIS save or take Psychic damage equal to the damage you took after halving. Recharge: Long Rest, or expend a Pact Magic slot." },
  { name: "Bewitching Magic", icon: "sparkles", cat: "action", uses: "After enchantment/illusion", minLevel: 14,
    desc: "Immediately after you cast an Enchantment or Illusion spell using an Action and a spell slot, you can cast Misty Step as part of that same action without expending a spell slot." },
]);

registerSubclassSheetEffects("Warlock_Archfey", [
  { type: "conditionImmunity", conditions: ["Charmed"], minLevel: 10, note: "Beguiling Defenses" },
]);
registerSubclassSheetResources("Warlock_Archfey", [
  { key: "archfey_steps",    name: "Steps of the Fey",    icon: "sparkles", recharge: "LR",
    max: (lv, { cha } = {}) => Math.max(1, cha ?? 0) },
  { key: "archfey_beguiling", name: "Beguiling Defenses", icon: "shield",   recharge: "LR", max: () => 1 },
]);

if (typeof registerSubclassRuntimeConfig === "function") {
  registerSubclassRuntimeConfig("Warlock_Archfey", {
    spellcasting: {
      alwaysPreparedSpells: [
        { name: 'Calm Emotions', minLevel: 3, level: 2, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Faerie Fire', minLevel: 3, level: 1, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Misty Step', minLevel: 3, level: 2, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Phantasmal Force', minLevel: 3, level: 2, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Sleep', minLevel: 3, level: 1, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Blink', minLevel: 5, level: 3, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Plant Growth', minLevel: 5, level: 3, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Dominate Beast', minLevel: 7, level: 4, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Greater Invisibility', minLevel: 7, level: 4, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Dominate Person', minLevel: 9, level: 5, source: 'Archfey', sourceType: 'subclass' },
        { name: 'Seeming', minLevel: 9, level: 5, source: 'Archfey', sourceType: 'subclass' }
      ],
    },
  });
}
// [SheetRuntime] END

}

