import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Monk_Elements", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Monk_Elements", [
  { name: "Manipulate Elements", icon: "", cat: "action", uses: "At will", minLevel: 3,
    desc: "You know the Elementalism cantrip. WIS is your spellcasting ability for it." },
  { name: "Elemental Attunement", icon: "", cat: "action", uses: "1 Focus Point", resKey: "ki", minLevel: 3,
    desc: "Start of your turn: spend 1 Focus Point. For 10 minutes (or until Incapacitated) gain — Reach: Unarmed Strike reach +10 ft; Elemental Strikes: when you hit with an Unarmed Strike, choose Acid/Cold/Fire/Lightning/Thunder as damage type instead of normal, and force a STR save or move the target up to 10 ft toward or away from you." },
  { name: "Elemental Burst", icon: "", cat: "action", uses: "2 Focus Points", resKey: "ki", minLevel: 6,
    damageFormula: ({ ownerLevel }) => {
      const lv = Number(ownerLevel || 1);
      const die = lv >= 17 ? 12 : lv >= 11 ? 10 : lv >= 5 ? 8 : 6;
      return `3d${die}`;
    },
    damageButtonLabel: ({ formula }) => `${formula} elemental`,
    damageKind: "damage",
    desc: "Magic action: expend 2 Focus Points. Choose Acid/Cold/Fire/Lightning/Thunder. 20-ft radius Sphere centered on a point within 120 ft: each creature makes a DEX save (spell save DC), fail = 3 × Martial Arts die damage, success = half." },
  { name: "Stride of the Elements", icon: "", cat: "action", uses: "Passive", minLevel: 11,
  passive: true,
    desc: "While Elemental Attunement is active: gain Fly Speed and Swim Speed equal to your Speed." },
  { name: "Elemental Epitome", icon: "", cat: "action", uses: "Passive", minLevel: 17,
  passive: true,
    desc: "While Elemental Attunement is active, also gain — Damage Resistance: choose Acid/Cold/Fire/Lightning/Thunder resistance (can change at the start of each of your turns); Destructive Stride: Step of the Wind gives +20 Speed until end of turn, and creatures within 5 ft that you enter take 1 Martial Arts die elemental damage (once per creature per turn); Empowered Strikes: once per turn, deal extra 1 Martial Arts die elemental damage on an Unarmed Strike hit." },
]);
if (typeof registerSubclassRuntimeConfig === "function") {
  registerSubclassRuntimeConfig("Monk_Elements", {
    spellcasting: {
      ability: "wis",
      alwaysKnownSpells: [
        { name: "Elementalism", minLevel: 3, level: 0 },
      ],
    },
  });
}

registerSubclassSheetEffects("Monk_Elements", [

  { type: "reach", value: 10, minLevel: 3, note: "Elemental Attunement: elemental reach while active." },
  { type: "damageTypeChoice", values: ["Acid", "Cold", "Fire", "Lightning", "Thunder"], minLevel: 3, note: "Elemental Attunement." },
  { type: "flySpeed", minLevel: 11, note: "Stride of the Elements." },
  { type: "resistance", damageTypes: ["Acid", "Cold", "Fire", "Lightning", "Thunder"], minLevel: 17, note: "Elemental Epitome while active." },
]);
// [SheetRuntime] END

}

