import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Monk_Mercy", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Monk_Mercy", [
  { name: "Implements of Mercy", icon: "", cat: "action", uses: "Passive", minLevel: 3,
  passive: true,
    desc: "Proficiency in Insight and Medicine skills, and proficiency with the Herbalism Kit." },
  { name: "Hand of Harm", icon: "", cat: "attack", uses: "1 Focus Point / turn", resKey: "ki", minLevel: 3,
    rollers: [{ kind: 'damage', formula: ({ ownerLevel }) => {
      const lv = Number(ownerLevel || 1);
      const die = lv >= 17 ? 12 : lv >= 11 ? 10 : lv >= 5 ? 8 : 6;
      return `1d${die}+WIS`;
    }, label: ({ formula }) => `+${formula} necrotic` }],
    desc: "Once per turn when you hit a creature with an Unarmed Strike and deal damage, spend 1 Focus Point to deal extra Necrotic damage equal to one roll of your Martial Arts die + your WIS modifier." },
  { name: "Hand of Healing", icon: "", cat: "action", uses: "1 Focus Point", resKey: "ki", minLevel: 3,
    desc: "Magic action: spend 1 Focus Point to touch a creature and restore HP equal to one roll of your Martial Arts die + your WIS modifier. When you use Flurry of Blows, you can replace one of the Unarmed Strikes with a use of this feature without expending a Focus Point for the healing." },
  { name: "Physician's Touch", icon: "", cat: "action", uses: "Passive", minLevel: 6,
  passive: true,
    desc: "Hand of Harm upgrade: also inflict the Poisoned condition until end of your next turn. Hand of Healing upgrade: also end one condition on the healed creature: Blinded, Deafened, Paralyzed, Poisoned, or Stunned." },
  { name: "Flurry of Healing and Harm", icon: "", cat: "bonus", uses: "WIS mod / LR", resKey: "mercy_flurry", minLevel: 11,
    desc: "When you use Flurry of Blows, you can replace each Unarmed Strike with Hand of Healing without expending Focus Points. Additionally, when a Flurry of Blows Unarmed Strike deals damage, you can use Hand of Harm without expending a Focus Point (still once per turn). These free-use benefits total WIS modifier uses per LR." },
  { name: "Hand of Ultimate Mercy", icon: "", cat: "action", uses: "1 / LR", resKey: "mercy_ultimate", minLevel: 17,
    desc: "Magic action: spend 5 Focus Points and touch the corpse of a creature that died within the past 24 hours. It returns to life with HP equal to 4d10 + your WIS modifier. The following conditions it died with are removed: Blinded, Deafened, Paralyzed, Poisoned, Stunned. Recharge: Long Rest." },
]);
registerSubclassSheetResources("Monk_Mercy", [
  { key: "mercy_flurry", name: "Flurry of Healing and Harm", icon: "sparkles", recharge: "LR",
    max: (lv, { wis } = {}) => Math.max(1, wis ?? 0) },
  { key: "mercy_ultimate", name: "Hand of Ultimate Mercy", icon: "heart", recharge: "LR", max: () => 1 },
]);
registerSubclassSheetProficiencies("Monk_Mercy", [
  { type: "skill",  values: ["Insight", "Medicine"], minLevel: 3 },
  { type: "tool",   values: ["Herbalism Kit"],        minLevel: 3 },
]);

registerSubclassSheetEffects("Monk_Mercy", [

  { type: "healing", minLevel: 3, note: "Hand of Healing." },
  { type: "necroticDamage", minLevel: 3, note: "Hand of Harm." },
  { type: "conditionRemoval", conditions: ["Blinded", "Deafened", "Paralyzed", "Poisoned", "Stunned"], minLevel: 6, note: "Physician's Touch." },
  { type: "revive", minLevel: 17, note: "Hand of Ultimate Mercy." },
]);
// [SheetRuntime] END

}

