import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Monk_Shadow", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Monk_Shadow", [
  { name: "Shadow Arts", icon: "", cat: "action", uses: "1 Focus Point (Darkness)", resKey: "ki", minLevel: 3,
    desc: "Three benefits — Darkness: spend 1 Focus Point to cast Darkness (no components); you can see inside the spell's area, and can move the Darkness area to a point within 60 ft of you at the start of each of your turns. Darkvision: you have Darkvision 60 ft (or +60 ft if you already have it). Shadowy Figments: you know Minor Illusion (WIS is spellcasting ability)." },
  { name: "Shadow Step", icon: "", cat: "bonus", uses: "At will", minLevel: 6,
    desc: "Bonus Action while entirely within Dim Light or Darkness: teleport up to 60 ft to an unoccupied space you can see that is also in Dim Light or Darkness. Gain Advantage on the next melee attack you make before the end of the current turn." },
  { name: "Improved Shadow Step", icon: "", cat: "bonus", uses: "1 Focus Point", resKey: "ki", minLevel: 11,
    desc: "When you use Shadow Step, you can expend 1 Focus Point to remove the dim light/darkness requirement for that use (teleport from any lighting condition). As part of this Bonus Action, you can also make one Unarmed Strike immediately after teleporting." },
  { name: "Cloak of Shadows", icon: "", cat: "action", uses: "3 Focus Points / 1 min", resKey: "ki", minLevel: 17,
    desc: "Magic action while entirely in Dim Light or Darkness: expend 3 Focus Points. For 1 minute, until Incapacitated, or until you end your turn in Bright Light, gain — Invisibility: Invisible condition; Partially Incorporeal: can move through occupied spaces as Difficult Terrain (shunted to last unoccupied space if you end turn in one); Shadow Flurry: use Flurry of Blows without expending Focus Points." },
]);
if (typeof registerSubclassRuntimeConfig === "function") {
  registerSubclassRuntimeConfig("Monk_Shadow", {
    spellcasting: {
      ability: "wis",
      alwaysKnownSpells: [
        { name: "Minor Illusion", minLevel: 3, level: 0 },
      ],
    },
  });
}

registerSubclassSheetEffects("Monk_Shadow", [

  { type: "darkvision", value: 60, additive: true, minLevel: 3, note: "Shadow Arts: Darkvision 60 ft or +60 ft if you already have it." },
  { type: "teleport", minLevel: 6, note: "Shadow Step." },
  { type: "invisibility", minLevel: 11, note: "Improved Shadow Step / Cloak of Shadows." },
  { type: "reactionAttack", minLevel: 17, note: "Opportunist." },
]);
// [SheetRuntime] END

}

