import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Rogue_Soulknife", function (cls, lv, specs) {});

// [SheetRuntime] START
registerSubclassSheetActions("Rogue_Soulknife", [
  {
    "name": "Psychic Blades",
    "icon": "",
    "cat": "attack",
    "uses": "Unlimited",
    "minLevel": 3,
    rollers: [{ kind: 'damage', formula: "1d6", label: ({ formula }) => `${formula} psychic` }],
    "rollLabelPrefix": "Psychic Blades",
    "desc": "Whenever you take the Attack action or make an Opportunity Attack, you can manifest a Psychic Blade in your free hand and attack with it (Finesse, range 60 ft, 1d6 psychic; disappears after the hit or miss). After attacking with a blade on your turn, you can make a melee or ranged attack with a second blade as a Bonus Action (damage die is 1d4 instead of 1d6; no ability modifier added to damage unless negative)."
  },
  {
    "name": "Psi-Bolstered Knack",
    "icon": "",
    "cat": "reaction",
    "uses": "1 Psionic Die",
    "resKey": "psionic_dice",
    "minLevel": 3,
    "desc": "If you fail an ability check using a skill or tool you are proficient in, roll one Psionic Energy Die and add the number rolled to the check, potentially turning failure into success. The die is expended only if the roll then succeeds."
  },
  {
    "name": "Psychic Whispers",
    "icon": "",
    "cat": "action",
    "uses": "1 Psionic Die",
    "resKey": "psionic_dice",
    "minLevel": 3,
    "desc": "Magic action: choose a number of willing creatures you can see up to your Proficiency Bonus, then roll one Psionic Energy Die. For a number of hours equal to the number rolled, you and the chosen creatures can speak telepathically with each other within 1 mile (no line of sight required). A creature can end the connection at any time (no action required)."
  },
  {
    "name": "Homing Strikes",
    "icon": "",
    "cat": "attack",
    "uses": "1 Psionic Die",
    "resKey": "psionic_dice",
    "minLevel": 9,
    "desc": "If you make an attack roll with your Psychic Blade and miss the target, you can roll one Psionic Energy Die and add the number rolled to the attack roll. If this causes the attack to hit, the die is expended; if the attack still misses, the die is not expended."
  },
  {
    "name": "Psychic Teleportation",
    "icon": "",
    "cat": "bonus",
    "uses": "1 Psionic Die",
    "resKey": "psionic_dice",
    "minLevel": 9,
    "desc": "Bonus Action: manifest a Psychic Blade, expend one Psionic Energy Die and roll it, then throw the blade to an unoccupied space you can see up to (10 × roll) feet away. You then teleport to that space, and the blade vanishes."
  },
  {
    "name": "Psychic Veil",
    "icon": "",
    "cat": "action",
    "uses": "1 / LR",
    "resKey": "psychic_veil",
    "minLevel": 13,
    "desc": "Magic action: gain the Invisible condition for 1 hour, or until you dismiss it (no action required). Ends early immediately after you deal damage to a creature or force a creature to make a saving throw. Once used, you can't use this feature again until you finish a Long Rest unless you expend one Psionic Energy Die (no action required) to restore it."
  },
  {
    "name": "Rend Mind",
    "icon": "",
    "cat": "attack",
    "uses": "1 / LR",
    "resKey": "rend_mind",
    "minLevel": 17,
    "desc": "When you use your Psychic Blades to deal Sneak Attack damage to a creature, you can force that target to make a WIS saving throw (DC = 8 + PB + DEX modifier). On a failed save, the target is Stunned for 1 minute; it repeats the save at the end of each of its turns, ending the effect on a success. 1/LR — you can restore this use by expending 3 Psionic Energy Dice (no action required)."
  }
]);
registerSubclassSheetResources("Rogue_Soulknife", [
  {
    "key": "psionic_dice",
    "name": "Psionic Energy Dice",
    "icon": "brain",
    "recharge": "LR",
    "die": (lv) => lv >= 17 ? "d12" : lv >= 11 ? "d10" : lv >= 5 ? "d8" : "d6",
    "max": (lv) => lv >= 17 ? 12 : lv >= 13 ? 10 : lv >= 9 ? 8 : lv >= 5 ? 6 : 4
  },
  {
    "key": "psychic_veil",
    "name": "Psychic Veil",
    "icon": "eye-off",
    "recharge": "LR",
    "max": () => 1
  },
  {
    "key": "rend_mind",
    "name": "Rend Mind",
    "icon": "brain",
    "recharge": "LR",
    "max": () => 1
  }
]);

registerSubclassSheetEffects("Rogue_Soulknife", [

  { type: "psychicWeapon", minLevel: 3, note: "Psychic Blades: finesse, thrown, psychic damage." },
  { type: "telepathy", minLevel: 3, note: "Psychic Whispers." },
  { type: "teleport", minLevel: 9, note: "Psychic Teleportation." },
  { type: "invisibility", minLevel: 13, note: "Psychic Veil." },
  { type: "stun", minLevel: 17, note: "Rend Mind." },
]);
// [SheetRuntime] END

}

