export {
  ARMOR_KIND_KEYS,
  armorSetTrainsKind,
  canonicalProperty,
  collectAllProficiencies,
  collectEquipmentProficiencySets,
  dedupeRules,
  formatRule,
  getArmorKindEntry,
  getArmorTrainingInfo,
  getUntrainedArmor,
  getWeaponCategory,
  getWeaponProficiencyInfo,
  hasNonProficientArmor,
  inferRuleFromLabel,
  itemHasProperty,
  labelToFormattedWeaponLabel,
  normalizeRule,
  normKey,
  processStructuredWeaponProficiencies,
  resolveWeaponProficiencyRules,
  ruleKey,
  weaponMatchesRule,
  weaponNameKeys,
} from './proficiency/index.js';
